# Generated by Django 5.0.7 on 2025-08-17 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anaconda_bus_APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الخطة (مثال: 3 أقساط كل شهر)')),
                ('number_of_installments', models.IntegerField(verbose_name='عدد الأقساط')),
                ('interval_days', models.IntegerField(default=30, verbose_name='الفاصل بين الأقساط (بالأيام)')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_plans', to='Anaconda_bus_APP.subscription')),
            ],
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(verbose_name='تاريخ الاستحقاق')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قيمة القسط')),
                ('is_paid', models.BooleanField(default=False, verbose_name='مدفوع')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='Anaconda_bus_APP.passenger')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='Anaconda_bus_APP.installmentplan')),
            ],
        ),
    ]
