# Generated by Django 5.0.7 on 2025-08-17 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anaconda_bus_APP', '0002_installmentplan_installment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'اضافة اشتراك للطلاب', 'verbose_name_plural': 'الاشتراكات'},
        ),
        migrations.AddField(
            model_name='subscription',
            name='installment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قيمة القسط'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_installment',
            field=models.BooleanField(default=False, verbose_name='دفع بالأقساط؟'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='next_payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ استحقاق القسط القادم'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='number_of_installments',
            field=models.IntegerField(blank=True, null=True, verbose_name='عدد الأقساط'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='paid_installments',
            field=models.IntegerField(default=0, verbose_name='عدد الأقساط المدفوعة'),
        ),
    ]
