# Generated by Django 5.0.7 on 2025-08-17 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anaconda_bus_APP', '0003_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='is_installment',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='next_payment_date',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='paid_installments',
        ),
        migrations.AddField(
            model_name='subscription',
            name='installment_enabled',
            field=models.BooleanField(default=False, verbose_name='خدمة القسط'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='number_of_installments',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد الأقساط'),
        ),
    ]
