# Generated by Django 5.0.7 on 2025-08-17 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Anaconda_bus_APP', '0004_remove_subscription_is_installment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': '  اضافه اشتراك للطلاب', 'verbose_name_plural': '  الاشتراكات '},
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='installment_amount',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='installment_enabled',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='number_of_installments',
        ),
    ]
