# Generated by Django 5.0.7 on 2025-08-19 07:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anaconda_bus_APP', '0005_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentplan',
            name='increase_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الزيادة %'),
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='installment_percentages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=5), default=list, size=None, verbose_name='النسب المئوية لكل دفعة (مجموعها = 100%)'),
        ),
    ]
