# Generated by Django 5.0.7 on 2025-08-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anaconda_bus_APP', '0006_installmentplan_increase_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formreservation',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('confirmed', 'تم التأكيد'), ('failed', 'فشل الدفع'), ('cash', 'نقداً'), ('subscription', 'اشتراك'), ('attended', 'حضر')], default='pending', max_length=20, verbose_name='حالة الدفع'),
        ),
    ]
