# Generated by Django 5.0.7 on 2025-08-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anaconda_bus_APP', '0007_alter_formreservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='allow_cash_payment',
            field=models.BooleanField(default=False, verbose_name='السماح بالدفع نقداً'),
        ),
    ]
