# Generated by Django 5.0.7 on 2025-08-23 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anaconda_bus_APP', '0008_category_allow_cash_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='formreservation',
            name='transaction_number',
            field=models.CharField(blank=True, error_messages={'unique': 'رقم المعاملة هذا مستخدم بالفعل في حجز آخر.'}, help_text='يستخدم لتسجيل رقم التحويل أو الدفع النقدي اليدوي', max_length=100, null=True, unique=True, verbose_name='رقم المعاملة (يدوي)'),
        ),
    ]
