# Generated by Django 5.0.7 on 2025-08-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anaconda_bus_APP', '0009_formreservation_transaction_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('active', 'نشط'), ('pending', 'قيد الانتظار'), ('completed', 'مكتمل'), ('cancelled', 'ملغي'), ('prepaid', 'مدفوع مسبقًا')], default='active', max_length=20, verbose_name='حاله الدفع'),
        ),
    ]
