# Generated by Django 5.0.7 on 2025-09-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anaconda_bus_APP', '0010_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='face_encoding',
            field=models.BinaryField(blank=True, null=True, verbose_name='تمثيل الوجه (FaceID)'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='face_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='faces/thumbnails/', verbose_name='صورة الطالب'),
        ),
    ]
