# Generated by Django 5.0.7 on 2025-09-04 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Anaconda_bus_APP', '0011_passenger_face_encoding_passenger_face_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='face_encoding',
        ),
    ]
