# Generated by Django 5.0.7 on 2025-09-06 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anaconda_bus_APP', '0012_remove_passenger_face_encoding'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط في الفرونت إند'),
        ),
        migrations.AddField(
            model_name='pickuplocation',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط في الفرونت إند'),
        ),
    ]
