# Generated by Django 5.0.7 on 2025-09-07 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Anaconda_bus_APP', '0013_city_is_active_pickuplocation_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='pickuplocation',
            name='is_active',
        ),
    ]
