# Generated by Django 5.0.7 on 2025-09-07 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anaconda_bus_APP', '0014_remove_city_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط في الفرونت إند'),
        ),
        migrations.AddField(
            model_name='pickuplocation',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط في الفرونت إند'),
        ),
    ]
