# Generated by Django 5.0.7 on 2025-09-07 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anaconda_bus_APP', '0015_city_is_active_pickuplocation_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'إدارة مدن الركوب في الفورم', 'verbose_name_plural': 'إدارة مدن الركوب في الفورم'},
        ),
        migrations.AlterModelOptions(
            name='formreservation',
            options={'verbose_name': 'إدارة حجوزات الفورم', 'verbose_name_plural': 'إدارة حجوزات الفورم'},
        ),
        migrations.AlterModelOptions(
            name='pickuplocation',
            options={'verbose_name': 'نقاط الركوب في الفورم', 'verbose_name_plural': 'إدارة نقاط الركوب في الفورم'},
        ),
        migrations.AddField(
            model_name='formreservation',
            name='going_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='going_reservations', to='Anaconda_bus_APP.city', verbose_name='مدينة الذهاب'),
        ),
        migrations.AddField(
            model_name='formreservation',
            name='going_pickup_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نقطة ركوب الذهاب'),
        ),
        migrations.AddField(
            model_name='formreservation',
            name='return_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_reservations', to='Anaconda_bus_APP.city', verbose_name='مدينة العودة'),
        ),
        migrations.AlterField(
            model_name='formreservation',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Anaconda_bus_APP.city', verbose_name='المدينة (قديم)'),
        ),
        migrations.AlterField(
            model_name='formreservation',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نقطة الركوب (قديم)'),
        ),
        migrations.AlterField(
            model_name='formreservation',
            name='trip_type',
            field=models.CharField(choices=[('ذهاب', 'ذهاب'), ('عودة', 'عودة'), ('ذهاب وعودة', 'ذهاب وعودة')], max_length=15, verbose_name='نوع الرحلة'),
        ),
        migrations.CreateModel(
            name='DropoffLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='أماكن النزول (كل مكان في سطر)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط في الفرونت إند')),
                ('trip_type', models.CharField(choices=[('ذهاب', 'نقاط نزول الذهاب'), ('عودة', 'نقاط نزول العودة')], max_length=10, verbose_name='نوع الرحلة')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropoff_locations', to='Anaconda_bus_APP.city', verbose_name='المدينة')),
            ],
            options={
                'verbose_name': 'نقطة نزول في الفورم',
                'verbose_name_plural': 'إدارة نقاط النزول في الفورم',
            },
        ),
    ]
