# Generated by Django 5.0.7 on 2025-09-08 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anaconda_bus_APP', '0016_alter_city_options_alter_formreservation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='one_way_price',
            field=models.DecimalField(decimal_places=2, default=25.0, max_digits=10, verbose_name='سعر رحلة الذهاب أو العودة'),
        ),
        migrations.AlterField(
            model_name='category',
            name='round_trip_price',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10, verbose_name='سعر رحلة الذهاب والعودة'),
        ),
    ]
