# Generated by Django 5.0.7 on 2025-09-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anaconda_bus_APP', '0017_alter_category_one_way_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscription_duration',
            field=models.IntegerField(blank=True, choices=[(12, 'باقه'), (7, 'أسبوع'), (30, 'شهر'), (48, 'نصف ترم'), (96, 'ترم كامل'), (192, 'سنة كاملة')], null=True, verbose_name='مدة الاشتراك'),
        ),
    ]
