# Generated by Django 5.0.7 on 2025-09-10 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anaconda_bus_APP', '0018_alter_subscription_subscription_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dropofflocation',
            name='city',
        ),
        migrations.AddField(
            model_name='dropofflocation',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dropoff_locations', to='Anaconda_bus_APP.category', verbose_name='الجامعة'),
        ),
    ]
