# Generated by Django 5.0.7 on 2025-09-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anaconda_bus_APP', '0019_remove_dropofflocation_city_dropofflocation_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropofflocation',
            name='trip_type',
            field=models.CharField(choices=[('ذهاب', 'نقاط نزول الذهاب'), ('عودة', 'نقاط ركوب العودة')], max_length=10, verbose_name='نوع الرحلة'),
        ),
    ]
