# Generated by Django 5.0.7 on 2025-09-11 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anaconda_bus_APP', '0020_alter_dropofflocation_trip_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Anaconda_bus_APP.category', verbose_name='الجامعة'),
        ),
    ]
