# Generated by Django 5.0.7 on 2025-09-15 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anaconda_bus_APP', '0021_trip_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickuplocation',
            name='name',
            field=models.TextField(verbose_name='أماكن الركوب (الاسم @ رابط جوجل مابس في كل سطر)'),
        ),
    ]
