# Generated by Django 5.0.7 on 2025-09-15 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anaconda_bus_APP', '0022_alter_pickuplocation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickuplocation',
            name='name',
            field=models.TextField(verbose_name='أماكن الركوب (كل مكان في سطر)'),
        ),
    ]
