# Generated by Django 5.0.7 on 2025-09-16 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anaconda_bus_APP', '0023_alter_pickuplocation_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_name', models.CharField(max_length=255, unique=True, verbose_name='اسم نقطة الركوب/النزول')),
                ('google_maps_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='رابط خرائط جوجل')),
            ],
            options={
                'verbose_name': 'رابط موقع جغرافي',
                'verbose_name_plural': 'إدارة روابط المواقع الجغرافية',
            },
        ),
    ]
