# Generated by Django 5.0.7 on 2025-09-16 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anaconda_bus_APP', '0024_locationlink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationlink',
            options={'ordering': ['point_name'], 'verbose_name': 'رابط موقع جغرافي', 'verbose_name_plural': 'إدارة روابط المواقع الجغرافية'},
        ),
        migrations.AddField(
            model_name='locationlink',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Anaconda_bus_APP.category', verbose_name='الجامعة المرتبطة'),
        ),
        migrations.AddField(
            model_name='locationlink',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Anaconda_bus_APP.city', verbose_name='المدينة المرتبطة'),
        ),
    ]
