# Generated by Django 5.0.7 on 2025-09-16 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Anaconda_bus_APP', '0025_alter_locationlink_options_locationlink_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationlink',
            options={'verbose_name': 'رابط موقع جغرافي', 'verbose_name_plural': 'إدارة روابط المواقع الجغرافية'},
        ),
        migrations.RemoveField(
            model_name='locationlink',
            name='category',
        ),
        migrations.RemoveField(
            model_name='locationlink',
            name='city',
        ),
    ]
