# Generated by Django 5.0.7 on 2025-09-17 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anaconda_bus_APP', '0026_alter_locationlink_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان الإعلان')),
                ('image', models.ImageField(upload_to='ads/', verbose_name='صورة الإعلان')),
                ('link', models.URLField(blank=True, null=True, verbose_name='رابط الإعلان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'إعلان',
                'verbose_name_plural': 'الإعلانات',
            },
        ),
    ]
