# Generated by Django 5.0.7 on 2026-02-01 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anaconda_bus_APP', '0028_whatsappotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_days', models.JSONField(default=list, help_text='قائمة بأيام الذهاب المختارة', verbose_name='أيام الذهاب')),
                ('departure_time', models.TimeField(blank=True, null=True, verbose_name='وقت الذهاب المفضل')),
                ('return_days', models.JSONField(default=list, help_text='قائمة بأيام العودة المختارة', verbose_name='أيام العودة')),
                ('return_time', models.TimeField(blank=True, null=True, verbose_name='وقت العودة المفضل')),
                ('pickup_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='نقطة الالتقاط')),
                ('dropoff_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='نقطة النزول')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Anaconda_bus_APP.category', verbose_name='الجامعة')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Anaconda_bus_APP.passenger', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'حجز أسبوعي',
                'verbose_name_plural': 'الحجوزات الأسبوعية',
                'unique_together': {('passenger', 'category')},
            },
        ),
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('saturday', 'السبت'), ('sunday', 'الأحد'), ('monday', 'الإثنين'), ('tuesday', 'الثلاثاء'), ('wednesday', 'الأربعاء'), ('thursday', 'الخميس'), ('friday', 'الجمعة')], max_length=10, verbose_name='اليوم')),
                ('trip_type', models.CharField(choices=[('departure', 'ذهاب'), ('return', 'عودة')], max_length=10, verbose_name='نوع الرحلة')),
                ('time', models.TimeField(verbose_name='الوقت')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Anaconda_bus_APP.category', verbose_name='الجامعة')),
            ],
            options={
                'verbose_name': 'جدول أسبوعي',
                'verbose_name_plural': 'الجداول الأسبوعية',
                'unique_together': {('category', 'day_of_week', 'trip_type', 'time')},
            },
        ),
    ]
