# Generated by Django 5.0.7 on 2026-02-07 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anaconda_bus_APP', '0029_weeklybooking_weeklyschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBotToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_username', models.CharField(max_length=100, unique=True, verbose_name='Bot Username')),
                ('bot_token', models.CharField(max_length=200, verbose_name='Bot Token')),
                ('webhook_url', models.URLField(blank=True, null=True, verbose_name='Webhook URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='telegram_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Telegram Token'),
        ),
    ]
