# Generated by Django 5.0.7 on 2026-02-07 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anaconda_bus_APP', '0030_telegrambottoken_booking_telegram_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
