# Generated by Django 5.0.7 on 2026-02-07 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anaconda_bus_APP', '0031_passenger_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='telegram_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
