# Generated by Django 5.0.7 on 2026-02-07 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=100, verbose_name='معرف الدردشة')),
                ('action', models.CharField(max_length=100, verbose_name='الإجراء')),
                ('booking_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الحجز')),
                ('details', models.TextField(blank=True, null=True, verbose_name='التفاصيل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإجراء')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'نشاط Telegram',
                'verbose_name_plural': 'أنشطة Telegram',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramUserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_id', models.CharField(max_length=100, verbose_name='رقم الحجز')),
                ('student_name', models.CharField(max_length=100, verbose_name='اسم الطالب')),
                ('trip_type', models.CharField(max_length=50, verbose_name='نوع الرحلة')),
                ('trip_date', models.DateField(verbose_name='تاريخ الرحلة')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('is_sent', models.BooleanField(default=False, verbose_name='تم الإرسال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إشعار Telegram',
                'verbose_name_plural': 'إشعارات Telegram',
                'ordering': ['-created_at'],
            },
        ),
    ]
