"""
Django settings for Main_Bus_Management project.

Generated by 'django-admin startproject' using Django 2.0.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY")
STRIPE_PUBLISHABLE_KEY = os.getenv("STRIPE_PUBLISHABLE_KEY")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")
ULTRAMSG_INSTANCE_ID = os.getenv("ULTRAMSG_INSTANCE_ID", "")
ULTRAMSG_API_TOKEN = os.getenv("ULTRAMSG_API_TOKEN", "")

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "django-insecure-change-me")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "*",
    "allen.allentravels.com",
    "80-ipz8hdpv7xxt21pnn2vrg-84e7dcb3.manusvm.computer",
]

CSRF_TRUSTED_ORIGINS = [
    "http://13.51.86.239",
    "https://bus.esolvelabs.com:4433/allen",
    "http://68.183.214.170:8082",
    "https://bus.esolvelabs.com:4433",
    "https://allen.allentravels.com",
    "https://80-ipz8hdpv7xxt21pnn2vrg-84e7dcb3.manusvm.computer",
]
CSRF_COOKIE_SECURE = False
CSRF_COOKIE_HTTPONLY = False
SESSION_COOKIE_SECURE = False

SECURE_BROWSER_XSS_FILTER = False
SECURE_CONTENT_TYPE_NOSNIFF = False
X_FRAME_OPTIONS = "DENY"
SECURE_SSL_REDIRECT = False
CSRF_COOKIE_SECURE = False
SESSION_COOKIE_SECURE = False
SECURE_HSTS_SECONDS = 31536000

INSTALLED_APPS = [
    "sslserver",
    "admin_interface",
    "colorfield",
    "Anaconda_bus_APP.apps.OrdersConfig",
    "Anaconda_bus_APP.templatetags",
    "telegram_bot.apps.TelegramBotConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    "django_celery_beat",
    "rest_framework",
]
ADMIN_CSS = "css/admin_custom.css"

MEDIA_URL = "/allen/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "Anaconda_bus_APP.middleware.check_face.FaceCheckMiddleware",
]

ROOT_URLCONF = "Main_Bus_Management.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.csrf",
            ],
        },
    },
]

WSGI_APPLICATION = "Main_Bus_Management.wsgi.application"

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB", "Allen_bus"),
        "USER": os.getenv("POSTGRES_USER", "postgres"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD", ""),
        "HOST": os.getenv("POSTGRES_HOST", "db"),
        "PORT": os.getenv("POSTGRES_PORT", "5432"),
        "CONN_MAX_AGE": 60,
    }
}

TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "")

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_L10N = True
USE_TZ = True

STATIC_URL = "/allen/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
LANGUAGES = [
    ("en", "English"),
    ("ar", "العربية"),
]
DATA_UPLOAD_MAX_NUMBER_FIELDS = 100000

LANGUAGE_CODE = "ar"
LOGIN_REDIRECT_URL = "index"
LOGIN_URL = "/allen/login/"
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

KASHIER_API_KEY = os.getenv("KASHIER_API_KEY", "")
KASHIER_SECRET_KEY = os.getenv("KASHIER_SECRET_KEY", "")
KASHIER_ACCOUNT_KEY = os.getenv("KASHIER_ACCOUNT_KEY", "")
KASHIER_MODE = os.getenv("KASHIER_MODE", "live")

GOOGLE_MAPS_API_KEY = os.getenv("GOOGLE_MAPS_API_KEY", "")

# Self-hosted maps stack
SELF_HOSTED_MAP_STYLE_URL = os.getenv(
    "SELF_HOSTED_MAP_STYLE_URL",
    "https://tiles.openfreemap.org/styles/positron",
)
SELF_HOSTED_MAP_DARK_STYLE_URL = os.getenv(
    "SELF_HOSTED_MAP_DARK_STYLE_URL",
    "https://basemaps.cartocdn.com/gl/dark-matter-gl-style/style.json",
)
SELF_HOSTED_TILE_URL = os.getenv("SELF_HOSTED_TILE_URL", "/tiles/{z}/{x}/{y}.png")
SELF_HOSTED_TILE_ATTRIBUTION = os.getenv(
    "SELF_HOSTED_TILE_ATTRIBUTION",
    '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
)
SELF_HOSTED_PHOTON_URL = os.getenv("SELF_HOSTED_PHOTON_URL", "")
SELF_HOSTED_NOMINATIM_URL = os.getenv("SELF_HOSTED_NOMINATIM_URL", "http://nominatim:8080")
SELF_HOSTED_VALHALLA_URL = os.getenv("SELF_HOSTED_VALHALLA_URL", "")
SELF_HOSTED_OSRM_URL = os.getenv("SELF_HOSTED_OSRM_URL", "http://osrm:5000")
PUBLIC_PHOTON_URL = os.getenv("PUBLIC_PHOTON_URL", "https://photon.komoot.io")
PUBLIC_OSRM_URL = os.getenv("PUBLIC_OSRM_URL", "https://router.project-osrm.org")

CELERY_BROKER_URL = "redis://redis:6379/0"
CELERY_RESULT_BACKEND = "redis://redis:6379/0"
